---
title: "Share Species Richness"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
#### library ####
library(shiny)
library(iNEXT)

f.fun = function(X,Y){
  f = c()
  # X = X[I] #X的共有物種
  # Y = Y[I] #Y的共有物種
  #f1.
  f[1] = sum(X==1 & Y!=0)
  #f.1
  f[2] = sum(X!=0 & Y==1)
  #f11
  f[3] = sum(X==1 & Y==1)
  #f2.
  f[4] = sum(X==2 & Y!=0)
  #f.2
  f[5] = sum(X!=0 & Y==2)
  #f22
  f[6] = sum(X==2 & Y==2)
  #f3.
  f[7] = sum(X==3 & Y!=0)
  #f.3
  f[8] = sum(X!=0 & Y==3)
  #f33
  f[9] = sum(X==3 & Y==3)
  #D
  f[10] = sum(X==0 | Y==0)
  return(f)
}
f.fun2 = function(X,Y){
  f = c()
  # X = X[I] #X的共有物種
  # Y = Y[I] #Y的共有物種
  #f1.
  f[1] = sum(X==1 & Y!=0)
  #f.1
  f[2] = sum(X!=0 & Y==1)
  #f11
  f[3] = sum(X==1 & Y==1)
  #f2.
  f[4] = sum(X==2 & Y!=0)
  #f.2
  f[5] = sum(X!=0 & Y==2)
  #f22
  f[6] = sum(X==2 & Y==2)
  #f3.
  f[7] = sum(X==3 & Y!=0)
  #f.3
  f[8] = sum(X!=0 & Y==3)
  #f33
  f[9] = sum(X==3 & Y==3)
  #D
  f[10] = sum(X==0 | Y==0)
  return(f)
}
f = function(X){
  f = c()
  f[1] = sum(X==1)
  f[2] = sum(X==2)
  f[3] = sum(X==3)
  f[4] = sum(X==4)
  f[5] = sum(X>=5)
  return(f)
}
obs = function(X,Y){
  I = which(X*Y>0)
  s.obs = length(I)
  return(s.obs)
}

#### with function ####
# estimater
Pan = function(X,Y,t1,t2){
  f = f.fun(X,Y)
  I = which(X*Y>0)
  s.obs = length(I)
  
  K1 = (t1-1)/t1
  K2 = (t2-1)/t2
  
  #
  if(f[4]==0 | f[5]==0 | f[6]==0){
    ans = s.obs + K1*f[1]*(f[1]-1)/(2*(f[4]+1)) +K2*f[2]*(f[2]-1)/(2*(f[5]+1)) + K1*K2*f[3]*(f[3]-1)/(4*(f[6]+1))
  }else{
    ans = s.obs + K1*(f[1]^2)/(2*f[4]) + K2*(f[2]^2)/(2*f[5]) + K1*K2*(f[3]^2)/(4*f[6]) 
  }
  return(ans)
} 
BB = function(X,Y,t1,t2){
  f = f.fun(X,Y)
  I = which(X*Y>0)
  s.obs = length(I)
  
  K1 = (t1-1)/t1
  K2 = (t2-1)/t2
  
  # bias大，SE小
  k1 = max(1/2,min(1,2*f[4]^2/(3*max(1,f[1])*max(1,f[7]))))
  k2 = max(1/2,min(1,2*f[5]^2/(3*max(1,f[2])*max(1,f[8]))))
  
  # bias小，SE大
  # k1 = max(1/2,2*f[4]^2/(3*f[1]*f[7]))
  # k2 = max(1/2,2*f[5]^2/(3*f[2]*f[8]))
  
  ans = if(f[4]==0 | f[5]==0 | f[6]==0){s.obs +
      K1*(f[1]*(f[1]-1)/(2*(f[4]+1)))*(2-k1) +
      K2*(f[2]*(f[2]-1)/(2*(f[5]+1)))*(2-k2) +
      K1*K2*(f[3]*(f[3]-1)/(4*(f[6]+1)))*(2-k1)*(2-k2)
  }else{s.obs +
      K1*(f[1]*(f[1]-1)/(2*f[4]))*(2-k1) +
      K2*(f[2]*(f[2]-1)/(2*f[5]))*(2-k2) +
      K1*K2*(f[3]*(f[3]-1)/(4*f[6]))*(2-k1)*(2-k2)
  }
  return(ans)
}

# var
var = function(s.obs,f1,f2,f3,f4,f5,f6,f7,f8,t1,t2){
  K1 = (t1-1)/t1
  K2 = (t2-1)/t2
  
  # bias大，SE小
  k1 = max(1/2,min(1,2*f4^2/(3*max(1,f1)*max(1,f7))))
  k2 = max(1/2,min(1,2*f5^2/(3*max(1,f2)*max(1,f8))))
  
  # bias小，SE大
  # k1 = max(1/2,2*f[4]^2/(3*f[1]*f[7]))
  # k2 = max(1/2,2*f[5]^2/(3*f[2]*f[8]))
  
  ans = if(f4==0 | f5==0 | f6==0){s.obs +
      K1*(f1*(f1-1)/(2*(f4+1)))*(2-k1) +
      K2*(f2*(f2-1)/(2*(f5+1)))*(2-k2) +
      K1*K2*(f3*(f3-1)/(4*(f6+1)))*(2-k1)*(2-k2)
  }else{s.obs +
      K1*(f1*(f1-1)/(2*f4))*(2-k1) +
      K2*(f2*(f2-1)/(2*f5))*(2-k2) +
      K1*K2*(f3*(f3-1)/(4*f6))*(2-k1)*(2-k2)
  }
  return(ans)
}
var_Pan = function(s.obs,f1,f2,f3,f4,f5,f6,t1,t2){
  K1 = (t1-1)/t1
  K2 = (t2-1)/t2
  
  #
  if(f4==0 | f5==0 | f6==0){
    ans = s.obs + K1*f1*(f1-1)/(2*(f4+1)) +K2*f2*(f2-1)/(2*(f5+1)) + K1*K2*f3*(f3-1)/(4*(f6+1))
  }else{
    ans = s.obs + K1*(f1^2)/(2*f4) + K2*(f2^2)/(2*f5) + K1*K2*(f3^2)/(4*f6) 
  }
  return(ans)
}


# Covmatrix
covmatrix = function(X,Y,s,O){
  f = c(f.fun(X,Y)) #用Sobs去建立covarance matrix
  f = c(f[1:8],s-O)
  cov_matrix = matrix(0, nrow = 9, ncol = 9)
  for(i in 1:length(f)){
    for(j in 1:length(f)){
      if(i == j){
        cov_matrix[i,i] = f[i]*(1-(f[i]/s))
      }else{
        cov_matrix[i,j] = -f[i]*(f[j]/s)
      }
    }
  }
  return(cov_matrix)
}
covmatrix_Pan = function(X,Y,s,O){
  f = c(f.fun(X,Y)) #用Sobs去建立covarance matrix
  f = c(f[1:6],s-O)
  cov_matrix = matrix(0, nrow = 7, ncol = 7)
  for(i in 1:length(f)){
    for(j in 1:length(f)){
      if(i == j){
        cov_matrix[i,i] = f[i]*(1-(f[i]/s))
      }else{
        cov_matrix[i,j] = -f[i]*(f[j]/s)
      }
    }
  }
  return(cov_matrix)
}


# population SD
SD  = function(X,Y,t1,t2,O,d){
  f = f.fun(X,Y)
  # f1=f[1];f2=f[2];f3=f[3];f4=f[4];f5=f[5]
  V = c((var(O,f[1]+d,f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2]+d,f[3],f[4],f[5],f[6],f[7],f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2],f[3]+d,f[4],f[5],f[6],f[7],f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2],f[3],f[4]+d,f[5],f[6],f[7],f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2],f[3],f[4],f[5]+d,f[6],f[7],f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2],f[3],f[4],f[5],f[6]+d,f[7],f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7]+d,f[8],t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,
        (var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8]+d,t1,t2)-var(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2))/d,-1)
  return(V)
}
SD_Pan  = function(X,Y,t1,t2,O,d){
  f = f.fun(X,Y)
  # f1=f[1];f2=f[2];f3=f[3];f4=f[4];f5=f[5];f6=f[6];f7=f[8];f7=f[8]
  V = c((var_Pan(O,f[1]+d,f[2],f[3],f[4],f[5],f[6],t1,t2)-var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6],t1,t2))/d,
        (var_Pan(O,f[1],f[2]+d,f[3],f[4],f[5],f[6],t1,t2)-var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6],t1,t2))/d,
        (var_Pan(O,f[1],f[2],f[3]+d,f[4],f[5],f[6],t1,t2)-var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6],t1,t2))/d,
        (var_Pan(O,f[1],f[2],f[3],f[4]+d,f[5],f[6],t1,t2)-var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6],t1,t2))/d,
        (var_Pan(O,f[1],f[2],f[3],f[4],f[5]+d,f[6],t1,t2)-var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6],t1,t2))/d,
        (var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6]+d,t1,t2)-var_Pan(O,f[1],f[2],f[3],f[4],f[5],f[6],t1,t2))/d,-1)
  return(V)
}


# SE
se = function(X,Y,t1,t2,O,E,d){
  sd = SD(X,Y,t1,t2,O,d)
  matrix = covmatrix(X,Y,E,O)
  SD = sqrt(abs(t(sd) %*% matrix %*% sd))
  return(SD)
}
se_Pan = function(X,Y,t1,t2,O,E_Pan,d){
  sd_Pan = SD_Pan(X,Y,t1,t2,O,d)
  matrix_Pan = covmatrix_Pan(X,Y,E_Pan,O)
  SD_Pan = sqrt(t(sd_Pan) %*% matrix_Pan %*% sd_Pan)
  return(SD_Pan)
}


# 95 % CI
CI_coverage = function(E,O,SD,s){
  R = as.numeric(exp(1.96*( log(1+SD^2/max(0.1^10,(E-O)^2)))^(1/2)))
  U = as.numeric(O+(E-O)*R)
  L = as.numeric(O+(E-O)/R)
  # U = as.numeric(E + (1.96*SD))
  # L = as.numeric(E - (1.96*SD))
  CI_coverage = sum(ifelse(L<s & s< U ,1,0)) / length(s)
  return(CI_coverage)
}

# cv
cv = function(X,t){
  C =  1 - (sum(X==1)/sum(X))
  Si = sum(X>0)
  f = c()
  for(i in 1:max(X)){
    f[i] = sum(X==i)
  }
  I = sum(c(1:length(f))*(c(1:length(f))-1)*f)
  II = sum(c(1:length(f))*f)
  III = sum(c(1:length(f))*f - 1)
  a = (Si/C)*(t/(t-1))* (I/(II*III))
  cv = max(a-1,0)
  return(sqrt(cv))
}

# 整理
realdata1 = function(P_X,P_Y){
  T1 = t1 = ncol(P_X)
  T2 = t2 = ncol(P_Y)
  
  # set sample
  X = rowSums(P_X)
  Y = rowSums(P_Y)
  
  # sample coverage
  CX = 1 - (sum(X==1)/sum(X))
  CY = 1 - (sum(Y==1)/sum(Y))
  
  # sample cv
  CvX = cv(X,t1)
  CvY = cv(Y,t2)
  
  # estimate
  E =  BB(X,Y,t1,t2)
  E_Pan = Pan(X,Y,t1,t2)
  O = obs(X,Y)
  
  d = .01
  
  # SD
  SD_ = as.numeric(se(X,Y,t1,t2,O,E,d))
  SD_Pan = as.numeric(se_Pan(X,Y,t1,t2,O,E_Pan,d))
  
  # log CI
  R = as.numeric(exp(1.96*( log(1+SD_^2/max(0.1^10,(E-O)^2)))^(1/2)))
  U = as.numeric(O+(E-O)*R)
  L = as.numeric(O+(E-O)/R)
  
  R1 = as.numeric(exp(1.96*( log(1+SD_Pan^2/max(0.1^10,(E_Pan-O)^2)))^(1/2)))
  U1 = as.numeric(O+(E_Pan-O)*R1)
  L1 = as.numeric(O+(E_Pan-O)/R1)
  
  I = cbind(O,E,SD_,L,U,CX,CY,CvX,CvY)
  II = cbind(O,E_Pan,SD_Pan,L1,U1,CX,CY,CvX,CvY)
  
  result = rbind(I,II)
  return(result)
}

#### without function ####
wor_share_2012 = function(X,Y,T1,T2,t1,t2){
  f = f.fun(X,Y)
  s.obs = obs(X,Y)
  
  q1 = t1/T1;q2 = t2/T2
  w1 = t1/(t1-1);w2 = t2/(t2-1)
  r1 = q1/(1-q1);r2 = q2/(1-q2)
  
  Q0_ = f[1]^2 / max(1,(2*w1*f[4] + r1*f[1]))
  Q_0 = f[2]^2 / max(1,(2*w2*f[5] + r2*f[2]))
  Q00 = f[3]^2 / max(1,(4*w1*w2*f[6] + 2*w1*r2*f[7] + 2*w2*r1*f[8] + r1*r2*f[3]))
  
  ans = s.obs + Q00 + Q0_ + Q_0
  
  return(ans)
}
wor_share = function(X,Y,T1,T2,t1,t2){
  f = f.fun(X,Y)
  s.obs = obs(X,Y)
  w1 = t1/T1
  w2 = t2/T2
  beta1 =(f[1]/max(1,f[4])-1)*t1
  beta2 =(f[2]/max(1,f[5])-1)*t2
  # beta1 =((f[1]-f[4])/max(1,f[4]))*t1
  # beta2 =((f[2]-f[5])/max(1,f[5]))*t2
  # beta1 =max(1,(f[1]/max(1,f[4])-1)*t1)
  # beta2 =max(1,(f[2]/max(1,f[5])-1)*t2)
  
  #Q00
  Q00 = ((t1-1)/t1) * ((t2-1)/t2)* (((beta1/t1)+1)*((T1-t1)/(T1+beta1))) * (((beta2/t2)+1)*((T2-t2)/(T2+beta2))) * f[3]
  # Q00 = ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f[3]
  
  #Q0+
  Q0_ = ((t1-1)/t1)*(((beta1/t1)+1)*((T1-t1)/(T1+beta1)))* f[1]
  
  # Q0_ = ((t1-1)/t1) * ((1-w1)*f[1]^2)/max(1,(f[4] + (w1*max(1,f[1]-f[4]))))
  
  #Q+0
  Q_0 = ((t2-1)/t2)* (((beta2/t2)+1)*((T2-t2)/(T2+beta2))) * f[2]
  
  # Q_0 = ((t2-1)/t2) * ((1-w2)*f[2]^2)/max(1,(f[5] + (w2*max(1,f[2]-f[5]))))
  
  # S
  ans = s.obs + Q00 + Q0_ + Q_0
  return(ans)
}
wor_share1 = function(X,Y,T1,T2,t1,t2){
  f = f.fun(X,Y)
  s.obs = obs(X,Y)
  w1 = t1/T1
  w2 = t2/T2
  # beta1 = t1*(sqrt(max(1,f[3]*f[7])/max(1,f[6]*f[8]))-1)
  # beta2 = t2*(sqrt(max(1,f[3]*f[8])/max(1,f[6]*f[7]))-1)
  # beta1 = max(1,t1*(sqrt(max(1,f[3]*f[7])/max(1,f[6]*f[8]))-1))
  # beta2 = max(1,t2*(sqrt(max(1,f[3]*f[8])/max(1,f[6]*f[7]))-1))
  beta1 = t1*(sqrt(max(1,f[3])*max(1,f[7])/max(1,f[6]*f[8]))-1)
  beta2 = t2*(sqrt(max(1,f[3])*max(1,f[8])/max(1,f[6]*f[7]))-1)
  
  #Q00
  Q00 = ((t1-1)/t1)* ((t2-1)/t2) * ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f[3]
  # Q00 = ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f[3]
  
  #Q0+
  Q0_ = ((t1-1)/t1)*(((beta1/t1)+1)*((T1-t1)/(T1+beta1)))* f[1]
  
  # Q0_ = ((t1-1)/t1) * ((1-w1)*f[1]^2)/max(1,(f[4] + (w1*max(1,f[1]-f[4]))))
  
  #Q+0
  Q_0 = ((t2-1)/t2)* (((beta2/t2)+1)*((T2-t2)/(T2+beta2))) * f[2]
  
  # Q_0 = ((t2-1)/t2) * ((1-w2)*f[2]^2)/max(1,(f[5] + (w2*max(1,f[2]-f[5]))))
  
  # S
  ans = s.obs + Q00 + Q0_ + Q_0
  return(ans)
}
wor_BB = function(X,Y,T1,T2,t1,t2){
  f = f.fun2(X,Y)
  I = which(X*Y>0)
  s.obs = length(I)
  
  K1 = (t1-1)/t1
  K2 = (t2-1)/t2
  
  # bias大，wor_se小
  k1 = max(1/2,min(1,2*f[4]^2/(3*max(1,f[1])*max(1,f[7]))))
  k2 = max(1/2,min(1,2*f[5]^2/(3*max(1,f[2])*max(1,f[8]))))
  
  # bias小，wor_se大
  # k1 = max(1/2,2*f[4]^2/(3*f[1]*f[7]))
  # k2 = max(1/2,2*f[5]^2/(3*f[2]*f[8]))
  
  ans = if(f[4]==0 | f[5]==0 | f[6]==0){s.obs +
      K1*(f[1]*(f[1]-1)/(2*(f[4]+1)))*(2-k1) +
      K2*(f[2]*(f[2]-1)/(2*(f[5]+1)))*(2-k2) +
      K1*K2*(f[3]*(f[3]-1)/(4*(f[6]+1)))*(2-k1)*(2-k2)
  }else{s.obs +
      K1*(f[1]*(f[1]-1)/(2*f[4]))*(2-k1) +
      K2*(f[2]*(f[2]-1)/(2*f[5]))*(2-k2) +
      K1*K2*(f[3]*(f[3]-1)/(4*f[6]))*(2-k1)*(2-k2)
  }
  return(ans)
}


# wor_var
wor_var = function(s.obs,f1,f2,f3,f4,f5,t1,t2,T1,T2){
  w1 = t1/T1
  w2 = t2/T2
  beta1 = max(0,((f1/max(1,f4))-1)*t1)
  beta2 = max(0,((f2/max(1,f4))-1)*t2)
  
  #Q00
  Q00 = ((t1-1)/t1)* ((t2-1)/t2)* ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f3
  
  #Q0+
  Q0_ = ((t1-1)/t1)*  ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * f1
  
  #Q+0
  Q_0 = ((t2-1)/t2)* ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f2
  
  ans = s.obs + Q00 + Q0_ + Q_0
  return(ans)
}
wor_var1 = function(s.obs,f1,f2,f3,f4,f5,f6,f7,f8,t1,t2,T1,T2){
  w1 = t1/T1
  w2 = t2/T2
  beta1 = max(0, -t1 + t1*sqrt((f3*f7)/max(1,(f6*f8))))
  beta2 = max(0, -t2 + t2*sqrt((f3*f8)/max(1,(f6*f7))))
  
  #Q00
  Q00 = ((t1-1)/t1)* ((t2-1)/t2)* ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f3
  
  #Q0+
  Q0_ = ((t1-1)/t1)*  ((beta1/t1 +1)*((T1-t1)/(T1+beta1))) * f1
  
  #Q+0
  Q_0 = ((t2-1)/t2)* ((beta2/t2 +1)*((T2-t2)/(T2+beta2))) * f2
  
  ans = s.obs + Q00 + Q0_ + Q_0
  return(ans)
}
wor_var12 = function(s.obs,f1,f2,f3,f4,f5,f6,f7,f8,t1,t2,T1,T2){
  q1 = t1/T1;q2 = t2/T2
  w1 = t1/(t1-1);w2 = t2/(t2-1)
  r1 = q1/(1-q1);r2 = q2/(1-q2)
  
  Q0_ = f1^2 / max(1,(2*w1*f4 + r1*f1))
  Q_0 = f2^2 / max(1,(2*w2*f5 + r2*f2))
  Q00 = f3^2 / max(1,(4*w1*w2*f6 + 2*w1*r2*f7 + 2*w2*r1*f8 + r1*r2*f3))
  
  ans = s.obs + Q00 + Q0_ + Q_0
  
  return(ans)
}
wor_var3 = function(s.obs,f1,f2,f3,f4,f5,f6,f7,f8,t1,t2,T1,T2){
  K1 = (t1-1)/t1
  K2 = (t2-1)/t2
  
  # bias大，wor_se小
  k1 = max(1/2,min(1,2*f4^2/(3*max(1,f1)*max(1,f7))))
  k2 = max(1/2,min(1,2*f5^2/(3*max(1,f2)*max(1,f8))))
  
  # bias小，wor_se大
  # k1 = max(1/2,2*f[4]^2/(3*f[1]*f[7]))
  # k2 = max(1/2,2*f[5]^2/(3*f[2]*f[8]))
  
  ans = if(f4==0 | f5==0 | f6==0){s.obs +
      K1*(f1*(f1-1)/(2*(f4+1)))*(2-k1) +
      K2*(f2*(f2-1)/(2*(f5+1)))*(2-k2) +
      K1*K2*(f3*(f3-1)/(4*(f6+1)))*(2-k1)*(2-k2)
  }else{s.obs +
      K1*(f1*(f1-1)/(2*f4))*(2-k1) +
      K2*(f2*(f2-1)/(2*f5))*(2-k2) +
      K1*K2*(f3*(f3-1)/(4*f6))*(2-k1)*(2-k2)
  }
  return(ans)
}


# wor_covmatrix
wor_covmatrix = function(X,Y,s,O){
  f = c(f.fun(X,Y)) #用Sobs去建立cowor_varance matrix
  f = c(f[1:5],s-O)
  cov_matrix = matrix(0, nrow = 6, ncol = 6)
  for(i in 1:length(f)){
    for(j in 1:length(f)){
      if(i == j){
        cov_matrix[i,i] = f[i]*(1-(f[i]/s))
      }else{
        cov_matrix[i,j] = -f[i]*(f[j]/s)
      }
    }
  }
  return(cov_matrix)
}
wor_covmatrix12 = function(X,Y,s,O){
  f = c(f.fun(X,Y)) #用Sobs去建立cowor_varance matrix
  f = c(f[1:8],s-O)
  cov_matrix = matrix(0, nrow = 9, ncol = 9)
  for(i in 1:length(f)){
    for(j in 1:length(f)){
      if(i == j){
        cov_matrix[i,i] = f[i]*(1-(f[i]/s))
      }else{
        cov_matrix[i,j] = -f[i]*(f[j]/s)
      }
    }
  }
  return(cov_matrix)
}
wor_covmatrix3 = function(X,Y,s,O){
  f = c(f.fun2(X,Y)) #用Sobs去建立cowor_varance matrix
  f = c(f[1:8],s-O)
  cov_matrix = matrix(0, nrow = 9, ncol = 9)
  for(i in 1:length(f)){
    for(j in 1:length(f)){
      if(i == j){
        cov_matrix[i,i] = f[i]*(1-(f[i]/s))
      }else{
        cov_matrix[i,j] = -f[i]*(f[j]/s)
      }
    }
  }
  return(cov_matrix)
}


# population wor_SD
wor_SD  = function(X,Y,t1,t2,T1,T2,O,d){
  f = f.fun(X,Y)
  # f1=f[1];f2=f[2];f3=f[3];f4=f[4];f5=f[5]
  V = c((wor_var(O,f[1]+d,f[2],f[3],f[4],f[5],t1,t2,T1,T2)-wor_var(O,f[1],f[2],f[3],f[4],f[5],t1,t2,T1,T2))/d,
        (wor_var(O,f[1],f[2]+d,f[3],f[4],f[5],t1,t2,T1,T2)-wor_var(O,f[1],f[2],f[3],f[4],f[5],t1,t2,T1,T2))/d,
        (wor_var(O,f[1],f[2],f[3]+d,f[4],f[5],t1,t2,T1,T2)-wor_var(O,f[1],f[2],f[3],f[4],f[5],t1,t2,T1,T2))/d,
        (wor_var(O,f[1],f[2],f[3],f[4]+d,f[5],t1,t2,T1,T2)-wor_var(O,f[1],f[2],f[3],f[4],f[5],t1,t2,T1,T2))/d,
        (wor_var(O,f[1],f[2],f[3],f[4],f[5]+d,t1,t2,T1,T2)-wor_var(O,f[1],f[2],f[3],f[4],f[5],t1,t2,T1,T2))/d,-1)
  return(V)
}
wor_SD1  = function(X,Y,t1,t2,T1,T2,O,d){
  f = f.fun(X,Y)
  # f1=f[1];f2=f[2];f3=f[3];f4=f[4];f5=f[5];f6=f[6];f7=f[8];f7=f[8]
  V = c((wor_var1(O,f[1]+d,f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2]+d,f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2],f[3]+d,f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2],f[3],f[4]+d,f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2],f[3],f[4],f[5]+d,f[6],f[7],f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6]+d,f[7],f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7]+d,f[8],t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8]+d,t1,t2,T1,T2)-wor_var1(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,-1)
  return(V)
}
wor_SD12  = function(X,Y,t1,t2,T1,T2,O,d){
  f = f.fun(X,Y)
  # f1=f[1];f2=f[2];f3=f[3];f4=f[4];f5=f[5];f6=f[6];f7=f[7];f8=f[8]
  V = c((wor_var12(O,f[1]+d,f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2]+d,f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2],f[3]+d,f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2],f[3],f[4]+d,f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2],f[3],f[4],f[5]+d,f[6],f[7],f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6]+d,f[7],f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7]+d,f[8],t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8]+d,t1,t2,T1,T2)-wor_var12(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,-1)
  return(V)
}
wor_SD3  = function(X,Y,t1,t2,T1,T2,O,d){
  f = f.fun2(X,Y)
  # f1=f[1];f2=f[2];f3=f[3];f4=f[4];f5=f[5]
  V = c((wor_var3(O,f[1]+d,f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2]+d,f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2],f[3]+d,f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2],f[3],f[4]+d,f[5],f[6],f[7],f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2],f[3],f[4],f[5]+d,f[6],f[7],f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6]+d,f[7],f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7]+d,f[8],t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,
        (wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8]+d,t1,t2,T1,T2)-wor_var3(O,f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],t1,t2,T1,T2))/d,-1)
  return(V)
}


# wor_se
wor_se = function(X,Y,t1,t2,T1,T2,O,E,d){
  wor_SD = wor_SD(X,Y,t1,t2,T1,T2,O,d)
  matrix = wor_covmatrix(X,Y,E,O)
  wor_SD = sqrt(abs(t(wor_SD) %*% matrix %*% wor_SD))
  return(wor_SD)
}
wor_se1 = function(X,Y,t1,t2,T1,T2,O,E1,d){
  wor_SD1 = wor_SD1(X,Y,t1,t2,T1,T2,O,d)
  matrix1 = wor_covmatrix12(X,Y,E1,O)
  wor_SD1 = sqrt(t(wor_SD1) %*% matrix1 %*% wor_SD1)
  return(wor_SD1)
}
wor_se12 = function(X,Y,t1,t2,T1,T2,O,E12,d){
  wor_SD12 = wor_SD12(X,Y,t1,t2,T1,T2,O,d)
  matrix12 = wor_covmatrix12(X,Y,E12,O)
  wor_SD12 = sqrt(t(wor_SD12) %*% matrix12 %*% wor_SD12)
  return(wor_SD12)
}
wor_se3 = function(X,Y,t1,t2,T1,T2,O,E3,d){
  wor_SD = wor_SD3(X,Y,t1,t2,T1,T2,O,d)
  matrix = wor_covmatrix3(X,Y,E3,O)
  wor_SD = sqrt(abs(t(wor_SD) %*% matrix %*% wor_SD))
  return(wor_SD)
}


# 95 % CI
CI_coverage1 = function(E,O,wor_SD_,s){
  U = as.numeric(E + (1.96*wor_SD_))
  L = as.numeric(E - (1.96*wor_SD_))
  CI_coverage = sum(ifelse((L<s)&(s<U), 1, 0)) / length(s)
  return(CI_coverage)
}
CI_coverage2 = function(E,O,wor_SD_,s){
  R = as.numeric(exp(1.96*( log(1+wor_SD_^2/max(0.1^10,(E-O)^2)))^(1/2)))
  U = as.numeric(O+(E-O)*R)
  L = as.numeric(O+(E-O)/R)
  CI_coverage = sum(ifelse((L<s)&(s<U), 1, 0)) / length(s)
  return(CI_coverage)
}


# 整理

realdata2 = function(P_X,P_Y,a){
  # T and t about sample fraction
  t1 = ncol(P_X)
  t2 = ncol(P_Y)
  T1 = ceiling(t1/a)
  T2 = ceiling(t2/a)
  
  # wor_set sample
  X = rowSums(P_X)
  Y = rowSums(P_Y)
  
  # sample coverage
  CX = 1 - (sum(X==1)/sum(X))
  CY = 1 - (sum(Y==1)/sum(Y))
  
  # sample cv
  CvX = cv(X,t1)
  CvY = cv(Y,t2)
  
  # estimate
  E = wor_share(X,Y,T1,T2,t1,t2)
  E1 = wor_share1(X,Y,T1,T2,t1,t2)
  E12 = wor_share_2012(X,Y,T1,T2,t1,t2)
  wor_BB = wor_BB(X,Y,T1,T2,t1,t2)
  O = obs(X,Y)
  
  
  d = .01
  
  # wor_SD
  wor_SD_ = wor_se(X,Y,t1,t2,T1,T2,O,E,d)
  wor_SD1_ = wor_se1(X,Y,t1,t2,T1,T2,O,E1,d)
  wor_SD12_ = wor_se12(X,Y,t1,t2,T1,T2,O,E12,d)
  wor_SDwor_BB_ = wor_se3(X,Y,t1,t2,T1,T2,O,E12,d)
  
  # log CI
  U = as.numeric(E + (1.96*wor_SD_))
  L = as.numeric(E - (1.96*wor_SD_))
  
  U1 = as.numeric(E1 + (1.96*wor_SD1_))
  L1 = as.numeric(E1 - (1.96*wor_SD1_))
  
  R12 = as.numeric(exp(1.96*( log(1+wor_SD12_^2/max(0.1^10,(E12-O)^2)))^(1/2)))
  U12 = as.numeric(O+(E12-O)*R12)
  L12 = as.numeric(O+(E12-O)/R12)
  
  Rwor_BB = as.numeric(exp(1.96*( log(1+wor_SDwor_BB_^2/max(0.1^10,(wor_BB-O)^2)))^(1/2)))
  Uwor_BB = as.numeric(O+(wor_BB-O)*Rwor_BB)
  Lwor_BB = as.numeric(O+(wor_BB-O)/Rwor_BB)
  
  
  I = cbind(O,CX,CY,CvX,CvY,E,wor_SD_,L,U)
  II = cbind(O,CX,CY,CvX,CvY,E1,wor_SD1_,L1,U1)
  IV = cbind(O,CX,CY,CvX,CvY,E12,wor_SD12_,L12,U12)
  V = cbind(O,CX,CY,CvX,CvY,wor_BB,wor_SDwor_BB_,Lwor_BB,Uwor_BB)
  
  result = rbind(I,II,IV,V)
  return(result)
}

```

Data Be Sample
=====================================
Column 1 {data-width=320}
-------------------------------------
    
### Data input
    
```{r}
radioButtons("sampling", label = "Sample way", 
             choices = list("with replacement"=1, "without replacement"=2), 
             selected = 1)
fileInput("P_X", label = "First population")
fileInput("P_Y", label = "Second population")
sliderInput("a", label = "Sample fraction", min = 0, 
        max = 1, value = .5)
```
   
Column 2 {.tabset}
-------------------------------------
   
### Summary

```{r}
X <- reactive({
    req(input$P_X)
    read.csv(input$P_X$datapath)
})

Y <- reactive({
    req(input$P_Y)
    read.csv(input$P_Y$datapath)
})

dat <- reactive({
  list(population_I = X(), population_II = Y())
})


  
renderTable({
  DataInfo(dat(), datatype="incidence_raw")
  })


```   
 
### Table
    
```{r}
X <- reactive({
    req(input$P_X)
    read.csv(input$P_X$datapath)
})

Y <- reactive({
    req(input$P_Y)
    read.csv(input$P_Y$datapath)
})


renderTable({
   if(input$sampling == 1){
    realdata1(X(),Y())
  }else{
    realdata2(X(),Y(),input$a)
  }
  })

```


Data Be Population
=====================================
   
Column 1 {.tabset}
-------------------------------------
   
### Summary

```{r}
X <- reactive({
    req(input$P_X)
    read.csv(input$P_X$datapath)
})

Y <- reactive({
    req(input$P_Y)
    read.csv(input$P_Y$datapath)
})

dat <- reactive({
  list(population_I = X(), population_II = Y())
})


  
renderTable({
  DataInfo(dat(), datatype="incidence_raw")
  })


```   
 
### Table
    
```{r}
X <- reactive({
    req(input$P_X)
    read.csv(input$P_X$datapath)
})

Y <- reactive({
    req(input$P_Y)
    read.csv(input$P_Y$datapath)
})

result <- reactive({
  if(input$sampling == 1){
    realdata1(X(),Y())
  }else{
    realdata2(X(),Y())
  }
  
})

renderTable({
  result()
  })
```

### Plot
    
```{r}
```

